#!/usr/bin/env bash

if [ -z "$(which git-secret)" ]; then exit 0; fi

## Hide all secret files using git-secret.
echo "Hiding secret files:"
git secret hide -m

if [ -n "$(git status --short)" ]; then
  git add $(git secret list | awk '{print $0 ".secret" }') .gitsecret/*
fi

## Separate pre-commit output from Git CLI output.
echo
