# docker-compose

version: "3"

services:
  express:
    image: stevenxie/express-starter:latest
    container_name: express-starter
    ports:
     - "80:3000"
    volumes:
     - express-vol:/app/dist
    restart: on-failure

volumes:
  express-vol:
