# docker-compose

version: "3"

services:
  express:
    image: stevenxie/express-starter:v1.0.1-prod
    container_name: express-starter
    ports:
     - "3000:3000"
    volumes:
     - express-vol:/app/dist
    restart: on-failure

volumes:
  express-vol:
